<script setup lang="ts">
import { Head } from '@inertiajs/vue3';
import { Braces, CheckCircle2, HandHeart, Lightbulb, MapPin, UserRound } from 'lucide-vue-next';
import DemoCta from '@/components/marketing/DemoCta.vue';
import SectionHeading from '@/components/marketing/SectionHeading.vue';

const principles = [
    { icon: Lightbulb, title: 'Start with the business problem', text: 'We first understand where staff time is being lost, where errors occur and what a useful result looks like.' },
    { icon: CheckCircle2, title: 'Prove value before scaling', text: 'Demonstrations and pilots help establish whether automation genuinely improves the workflow.' },
    { icon: HandHeart, title: 'Keep humans in control', text: 'Automation should support business teams, not hide important decisions behind technology.' },
];
</script>

<template>
    <Head title="About"><meta name="description" content="Learn how DocuFlow UG is building practical, research-led document automation for Ugandan businesses." /></Head>
    <section class="relative overflow-hidden bg-blue-600 px-5 py-20 text-white sm:px-6 lg:px-8 lg:py-28"><div class="absolute -top-28 -right-20 size-96 rounded-full bg-cyan-400/20 blur-3xl" /><div class="relative mx-auto max-w-4xl text-center"><p class="text-sm font-extrabold tracking-[0.14em] text-blue-100 uppercase">About DocuFlow UG</p><h1 class="mt-4 text-4xl font-extrabold tracking-[-0.045em] text-balance sm:text-5xl lg:text-6xl">Local automation built for practical business problems</h1><p class="mx-auto mt-6 max-w-3xl text-lg leading-8 text-blue-100">DocuFlow UG focuses on repetitive document work that consumes time, introduces errors and slows down otherwise capable teams.</p></div></section>

    <section class="px-5 py-20 sm:px-6 lg:px-8 lg:py-28"><div class="mx-auto grid max-w-7xl gap-14 lg:grid-cols-2 lg:items-center"><div><SectionHeading eyebrow="Our story" title="Built to make everyday document work more manageable" description="DocuFlow UG was developed to address repetitive business-document processing experienced by Ugandan SMEs. It has been built and tested as a functioning automation system—not merely described as an idea." /><p class="mt-5 leading-8 text-slate-600">The goal is straightforward: understand the work first, automate the repetitive parts carefully, and keep the result useful to the people responsible for the business process.</p></div><div class="rounded-3xl border border-blue-100 bg-blue-50 p-8 sm:p-10"><MapPin class="size-9 text-blue-700" /><p class="mt-6 text-sm font-bold tracking-widest text-blue-700 uppercase">Grounded in Uganda</p><h2 class="mt-3 text-3xl font-extrabold tracking-tight text-slate-950">Research before assumptions</h2><p class="mt-4 leading-8 text-slate-600">Initial interviews in Mbarara helped identify accuracy, security, reliability and processing time as important adoption considerations.</p></div></div></section>

    <section class="bg-slate-50 px-5 py-20 sm:px-6 lg:px-8 lg:py-28"><div class="mx-auto max-w-7xl"><SectionHeading eyebrow="Our approach" title="Practical principles guide every workflow" centered /><div class="mt-12 grid gap-5 md:grid-cols-3"><article v-for="principle in principles" :key="principle.title" class="rounded-2xl border border-slate-200 bg-white p-7"><span class="grid size-12 place-items-center rounded-xl bg-blue-50 text-blue-700"><component :is="principle.icon" class="size-6" /></span><h2 class="mt-6 text-xl font-extrabold text-slate-950">{{ principle.title }}</h2><p class="mt-3 text-sm leading-7 text-slate-600">{{ principle.text }}</p></article></div></div></section>

    <section class="px-5 py-20 sm:px-6 lg:px-8 lg:py-28"><div class="mx-auto max-w-7xl"><SectionHeading eyebrow="Research-led development" title="Customer concerns shaped the offer" description="Before finalizing the launch offer, DocuFlow interviewed five businesses in Mbarara." /><div class="mt-10 grid gap-5 lg:grid-cols-[1.2fr_0.8fr]"><div class="rounded-3xl bg-slate-950 p-8 text-white sm:p-10"><p class="text-xl leading-9 font-semibold">Every respondent reported monthly document-processing problems or errors. Their feedback pushed accuracy, security, reliability and processing time to the centre of product and pricing decisions.</p><p class="mt-5 text-sm leading-7 text-slate-400">This is a five-business research sample. We present it as early product research, not proof of market dominance or guaranteed outcomes.</p></div><div class="grid grid-cols-2 gap-4"><div class="rounded-2xl border border-slate-200 p-6"><p class="text-4xl font-extrabold text-blue-600">5/5</p><p class="mt-2 text-sm font-semibold text-slate-600">reported monthly problems</p></div><div class="rounded-2xl border border-slate-200 p-6"><p class="text-4xl font-extrabold text-blue-600">3.8/5</p><p class="mt-2 text-sm font-semibold text-slate-600">average automation interest</p></div></div></div></div></section>

    <section class="bg-blue-50 px-5 py-20 sm:px-6 lg:px-8"><div class="mx-auto grid max-w-7xl gap-8 rounded-3xl bg-white p-8 shadow-sm sm:p-10 lg:grid-cols-[auto_1fr] lg:items-center"><span class="grid size-20 place-items-center rounded-2xl bg-blue-600 text-white"><UserRound class="size-10" /></span><div><p class="text-sm font-bold tracking-widest text-blue-700 uppercase">Founder / Automation Developer</p><h2 class="mt-2 text-3xl font-extrabold text-slate-950">Lawrence Kawalya</h2><p class="mt-4 max-w-4xl leading-8 text-slate-600">Lawrence works across AI-assisted workflow automation, n8n, API integration, document processing, workflow monitoring and practical business-process automation.</p><div class="mt-5 inline-flex items-center gap-2 rounded-full bg-slate-100 px-4 py-2 text-sm font-bold text-slate-700"><Braces class="size-4 text-blue-600" /> n8n · AI APIs · monitored workflow infrastructure</div></div></div></section>
    <DemoCta title="Talk to us about your workflow" />
</template>
